# プロジェクト構成・設定
name: Sample
configs:
  Debug: debug
  Release: release
options:
  groupSortPosition: top
attributes:
  ORGANIZATIONNAME: matsuokah
fileGroups:
    - Sample
    - SampleTests

# ターゲット
targets:
  Sample:
    type: application
    platform: iOS
    dependencies:
      - target: Utility
      - carthage: Realm
      - carthage: RealmSwift
    sources:
      - path: Sample
    configFiles:
      Debug: Sample/Debug.xcconfig
      Release: Sample/Release.xcconfig
  SampleTests:
    type: bundle.unit-test
    platform: iOS
    dependencies:
      - target: Sample
    settings:
      TEST_HOST: $(BUILT_PRODUCTS_DIR)/Sample.app/Sample
      INFOPLIST_FILE: SampleTests/Info.plist
    sources:
      - SampleTests
  Utility:
    type: framework
    platform: iOS
    settings:
      INFOPLIST_FILE: Utility/Info.plist
    sources:
      - Utility

# スキーム
schemes:
  Sample:
    build:
      targets:
        Sample: all
    run:
      config: Debug
    test:
      config: Debug
      gatherCoverageData: true
      targets:
          - SampleTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
